import type { MuscleSlug } from './types';

export const EXERCISE_MAP: Record<string, Partial<Record<MuscleSlug, number>>> = {
  Squat:               { quadriceps: 1, gluteal: 1, hamstring: 0.5, 'lower-back': 0.5 },
  'Leg Press':         { quadriceps: 1, gluteal: 0.5 },
  'Walking Lunge':     { quadriceps: 1, gluteal: 1, hamstring: 0.5 },
  'Bulgarian Split Squat': { quadriceps: 1, gluteal: 0.75, hamstring: 0.5 },
  'Leg Extension':     { quadriceps: 1 },
  'Leg Curl':          { hamstring: 1 },
  'Romanian Deadlift': { hamstring: 1, gluteal: 1, 'lower-back': 0.5 },
  'Hip Thrust':        { gluteal: 1, hamstring: 0.5 },
  'Calf Raise':        { calves: 1, tibialis: 0.25 },
  'Bench Press':       { chest: 1, deltoids: 0.5, triceps: 0.5 },
  'Incline Press':     { chest: 1, deltoids: 0.75, triceps: 0.5 },
  'Dumbbell Fly':      { chest: 1, deltoids: 0.25 },
  'Overhead Press':    { deltoids: 1, triceps: 0.5, trapezius: 0.5 },
  'Lateral Raise':     { deltoids: 1 },
  'Face Pull':         { deltoids: 0.5, trapezius: 0.5, 'upper-back': 0.5 },
  'Lat Pulldown':      { 'upper-back': 1, biceps: 0.5 },
  'Pull Up':           { 'upper-back': 1, biceps: 0.75 },
  'Barbell Row':       { 'upper-back': 1, biceps: 0.5, trapezius: 0.5 },
  'Cable Row':         { 'upper-back': 1, biceps: 0.5 },
  Deadlift:            { hamstring: 1, gluteal: 1, 'lower-back': 1, trapezius: 0.5, forearm: 0.5 },
  'Bicep Curl':        { biceps: 1, forearm: 0.5 },
  'Hammer Curl':       { biceps: 0.75, forearm: 0.75 },
  'Tricep Pushdown':   { triceps: 1 },
  'Skull Crusher':     { triceps: 1 },
  Dip:                 { triceps: 1, chest: 0.5, deltoids: 0.25 },
  Crunch:              { abs: 1, obliques: 0.5 },
  Plank:               { abs: 1, obliques: 0.5, 'lower-back': 0.25 },
  'Russian Twist':     { obliques: 1, abs: 0.5 },
  'Cable Woodchop':    { obliques: 1, abs: 0.5 },
  Shrug:               { trapezius: 1 },
  'Wrist Curl':        { forearm: 1 },
  'Adductor Machine':  { adductors: 1 },
};

export const MUSCLE_LABELS: Record<MuscleSlug, string> = {
  chest: 'Chest',
  obliques: 'Obliques',
  abs: 'Abs',
  biceps: 'Biceps',
  triceps: 'Triceps',
  trapezius: 'Traps',
  deltoids: 'Delts',
  quadriceps: 'Quads',
  tibialis: 'Tibialis',
  calves: 'Calves',
  forearm: 'Forearms',
  adductors: 'Adductors',
  'upper-back': 'Upper Back',
  'lower-back': 'Lower Back',
  gluteal: 'Glutes',
  hamstring: 'Hamstrings',
};
