# Alembic configuration file for INÖ Fitness Database

[alembic]
# path to migration scripts
sqlalchemy.url = driver://user:password@localhost/dbname
# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(asctime)s_%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to datetime.tz module. If left blank
# the migration files are created without timezone info
# timezone =

# max length of characters to apply to the
# "slug" field
# truncate_slug_len = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# Loggers to configure [key_list]:
# sqlalchemy.engine - all SQL emitted (log_level=INFO)
# alembic - general alembic logging (log_level=INFO)
#
# [loggers]
# keys = sqlalchemy,alembic
#
# [handlers]
# keys = console
#
# [formatters]
# keys = generic
#
# [logger_sqlalchemy]
# level = WARN
# handlers =
# qualname = sqlalchemy.engine
#
# [logger_alembic]
# level = INFO
# handlers =
# qualname = alembic
#
# [handler_console]
# class = StreamHandler
# args = (sys.stderr,)
# level = NOTSET
# formatter = generic
#
# [formatter_generic]
# format = %(levelname)-5.5s [%(name)s] %(message)s
# datefmt = %H:%M:%S

[sqlalchemy]
# the SQLAlchemy URL scheme to use when generating the
# initial migration. See the SQLAlchemy docs for examples
# of different URL schemes
sqlalchemy.url = sqlite:///ino_fitness.db

[loggers]
keys = sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
